name: NET Framework 45 Web Forms

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: 'true'
         token: ${{ secrets.PAT_TOKEN }}
         #repository: rheaton-ras/ras-net-framework-submodule
         #path: ras-net-framework-submodule
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    #- name: Navigate to Workspace
    #  run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore NetFramework45WebForms/NetFramework45WebForms.sln

    - name: Build Solution
      run: |
        msbuild.exe NetFramework45WebForms/NetFramework45WebForms.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: Azure
      uses: azure/webapps-deploy@v1
      with:
        app-name: net-framework-45-web-forms
        publish-profile: ${{ secrets.DEV }}
        package: ./_build
